ALTER TABLE air_dryer
ADD COLUMN adsullair23_dewpoint_temp DECIMAL(5, 2),
ADD COLUMN adsullair23_reflow_press DECIMAL(5, 2),
ADD COLUMN adsullair23_pre_filter ENUM('HJ','M'),
ADD COLUMN adsullair23_after_filter ENUM('HJ','M'),
ADD COLUMN adsullair23_autodrain_solenoid ENUM('B','R'),
ADD COLUMN adsullair23_vibration ENUM('H','S','T'),
ADD COLUMN adsullair24_dewpoint_temp DECIMAL(5, 2),
ADD COLUMN adsullair24_reflow_press DECIMAL(5, 2),
ADD COLUMN adsullair24_pre_filter ENUM('HJ','M'),
ADD COLUMN adsullair24_after_filter ENUM('HJ','M'),
ADD COLUMN adsullair24_autodrain_solenoid ENUM('B','R'),
ADD COLUMN adsullair24_vibration ENUM('H','S','T'),
ADD COLUMN adsullair27_dewpoint_temp DECIMAL(5, 2),
ADD COLUMN adsullair27_reflow_press DECIMAL(5, 2),
ADD COLUMN adsullair27_pre_filter ENUM('HJ','M'),
ADD COLUMN adsullair27_after_filter ENUM('HJ','M'),
ADD COLUMN adsullair27_autodrain_solenoid ENUM('B','R'),
ADD COLUMN adsullair27_vibration ENUM('H','S','T'),
ADD COLUMN adsullair33_dewpoint_temp DECIMAL(5, 2),
ADD COLUMN adsullair33_reflow_press DECIMAL(5, 2),
ADD COLUMN adsullair33_pre_filter ENUM('HJ','M'),
ADD COLUMN adsullair33_after_filter ENUM('HJ','M'),
ADD COLUMN adsullair33_autodrain_solenoid ENUM('B','R'),
ADD COLUMN adsullair33_vibration ENUM('H','S','T'),
ADD COLUMN adaugust28_dewpoint_temp DECIMAL(5, 2),
ADD COLUMN adaugust28_reflow_press DECIMAL(5, 2),
ADD COLUMN adaugust28_pre_filter ENUM('HJ','M'),
ADD COLUMN adaugust28_after_filter ENUM('HJ','M'),
ADD COLUMN adaugust28_autodrain_solenoid ENUM('B','R'),
ADD COLUMN adaugust28_vibration ENUM('H','S','T'),
ADD COLUMN adaugust29_dewpoint_temp DECIMAL(5, 2),
ADD COLUMN adaugust29_reflow_press DECIMAL(5, 2),
ADD COLUMN adaugust29_pre_filter ENUM('HJ','M'),
ADD COLUMN adaugust29_after_filter ENUM('HJ','M'),
ADD COLUMN adaugust29_autodrain_solenoid ENUM('B','R'),
ADD COLUMN adaugust29_vibration ENUM('H','S','T'),
ADD COLUMN adaugust30_dewpoint_temp DECIMAL(5, 2),
ADD COLUMN adaugust30_reflow_press DECIMAL(5, 2),
ADD COLUMN adaugust30_pre_filter ENUM('HJ','M'),
ADD COLUMN adaugust30_after_filter ENUM('HJ','M'),
ADD COLUMN adaugust30_autodrain_solenoid ENUM('B','R'),
ADD COLUMN adaugust30_vibration ENUM('H','S','T'),
ADD COLUMN adaugust31_dewpoint_temp DECIMAL(5, 2),
ADD COLUMN adaugust31_reflow_press DECIMAL(5, 2),
ADD COLUMN adaugust31_pre_filter ENUM('HJ','M'),
ADD COLUMN adaugust31_after_filter ENUM('HJ','M'),
ADD COLUMN adaugust31_autodrain_solenoid ENUM('B','R'),
ADD COLUMN adaugust31_vibration ENUM('H','S','T'),